### ISSUE TITLE
GRAPH 20 Pattern Matching with Cypher SPS01.sql file has typo error

### ISSUE THREAD

**Issue by abutalha89** [saphanaacademy/Graph#2]
I tried executing  GRAPH 20 Pattern Matching with Cypher SPS01.sql file and I faced error. The cause for error is on line 30:

>  MATCH (a)-[e]-(b) 

It should be MATCH (a)-[e]-**>**(b) . ">" is missing in the equation.
Please look into the line 2 and 30.

**Comment by saphanaacademy** [comment]
Hi,
MATCH (a)-[e]-(b) syntax (without the >) is how HANA supports undirected edges and is was introduced with SAP HANA 2 SPS01 (this syntax will not work in prior releases). Are you sure to be using SAP HANA 2 SPS01? You should be able to verify this by executing SELECT VERSION FROM "SYS"."M_DATABASE"
Thanks,

**Comment by abutalha89** [comment]
Hello
Thank you for explanation. I was using SAP HANA 2 SPS00.
Thanks,
