### ISSUE TITLE
Graph Viewer - unable to move nodes

### ISSUE THREAD

**Issue by DaveRUK** [saphanaacademy/Graph#3]
Hi,

Have searched online but found very little information on this.

I have created a graph workspace that represents our virtual data model, which has worked as expected.  I was experimenting with the various setting in the FORCE LAYOUT properties and am now unable to move any of the NODES.  Have my settings in effect disabled this function and if so, how do I enable it again?

Current settings shown below...

![image](https://user-images.githubusercontent.com/38691656/40649029-cb2879c8-6327-11e8-8527-c6e0571846e9.png)

TIA
Dave

**Comment by saphanaacademy** [comment]
Hi Dave,
Thanks for asking however could you post the question on the [HANA](https://www.sap.com/community/topic/hana.html) area of the SAP Community? Ideally with more info on exact HANA version and a full screenshot?
Thanks,
Philip

**Comment by DaveRUK** [comment]
No worries - will do

link below

https://answers.sap.com/questions/529601/graph-viewer-unable-to-move-nodes.html
